In [2]:
# Read the link for NumPy lib basics understanding
# https://numpy.org/doc/stable/user/absolute_beginners.html
import numpy as np
a = np.array([0., 0., 0.])
a

array([0., 0., 0.])

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.empty(2) # may vary

array([-6.71438021e+215, -1.55120414e-010])

In [5]:
# You can create an array with a range of elements:
np.arange(4)

array([0, 1, 2, 3])

In [6]:
# And even an array that contains a range of evenly spaced intervals. 
# To do this, you will specify the first number, last number, and the step size.
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [7]:
# You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
aa = np.array([1, 2, 3, 4, 5, 6])
aa.shape

(6,)

In [9]:
aa2 = aa[np.newaxis, :]
aa2.shape

(1, 6)

In [10]:
# Or, for a column vector, you can insert an axis along the second dimension:

col_vector = aa[:, np.newaxis]
col_vector.shape

(6, 1)

# creating an Arrary

In [3]:
# 1-D array
food=np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(price)

3

In [8]:
len(food)

3

In [9]:
price[2]

5

In [10]:
food[0]

'pakora'

In [12]:
price[0:]

array([5, 5, 5])

In [14]:
food[2]

'raita'

In [15]:
price.mean()

5.0

In [16]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.empty(5) # search why 1 1 1 1 1 

array([1., 1., 1., 1., 1.])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1,20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [29]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [39]:
# linear space
np.linspace(1,20, num=7)

array([ 1.        ,  4.16666667,  7.33333333, 10.5       , 13.66666667,
       16.83333333, 20.        ])

In [42]:
# specify your data
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [43]:
# specify your data
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

Array Funcitons

In [46]:
a=np.array([10,12,15,2,4,100,293,4,0.55])
a

array([ 10.  ,  12.  ,  15.  ,   2.  ,   4.  , 100.  , 293.  ,   4.  ,
         0.55])

In [48]:
a.sort()
a

array([  0.55,   2.  ,   4.  ,   4.  ,  10.  ,  12.  ,  15.  , 100.  ,
       293.  ])

In [51]:
b=([3,5,6,1,2,5,6,5,3])
b

[3, 5, 6, 1, 2, 5, 6, 5, 3]

In [52]:
c=np.concatenate((a,b))
c

array([  0.55,   2.  ,   4.  ,   4.  ,  10.  ,  12.  ,  15.  , 100.  ,
       293.  ,   3.  ,   5.  ,   6.  ,   1.  ,   2.  ,   5.  ,   6.  ,
         5.  ,   3.  ])

# 2-D arrays

In [54]:
x=np.array([[1,2,3,4,5], [5,4,3,2,1]])
x

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [55]:
y=np.array([[2,4],[3,66]])
y

array([[ 2,  4],
       [ 3, 66]])

In [56]:
np.concatenate((x,y)) # this will error as the dimensions are not same of the arrays, 

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

In [57]:
z=np.array([[2,4,100, 23, 24],[3,66,111,978,2349]])
z

array([[   2,    4,  100,   23,   24],
       [   3,   66,  111,  978, 2349]])

In [61]:
np.concatenate((x,z))

array([[   1,    2,    3,    4,    5],
       [   5,    4,    3,    2,    1],
       [   2,    4,  100,   23,   24],
       [   3,   66,  111,  978, 2349]])

In [62]:
np.concatenate((x,z), axis=0)

array([[   1,    2,    3,    4,    5],
       [   5,    4,    3,    2,    1],
       [   2,    4,  100,   23,   24],
       [   3,   66,  111,  978, 2349]])

In [63]:
np.concatenate((x,z), axis=1)

array([[   1,    2,    3,    4,    5,    2,    4,  100,   23,   24],
       [   5,    4,    3,    2,    1,    3,   66,  111,  978, 2349]])

In [64]:
zz=np.array([[1,2,3],[4,5,6],[7,8,9]])
zz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
zz.ndim

2

In [69]:
ss=np.array([[[1,2,3],[1,1,1]],[[4,5,6],[2,2,2]],[[7,8,9],[3,3,3]]])
ss

array([[[1, 2, 3],
        [1, 1, 1]],

       [[4, 5, 6],
        [2, 2, 2]],

       [[7, 8, 9],
        [3, 3, 3]]])

In [70]:
ss.ndim

3

In [73]:
sss=np.array([[[1,2,3],[1,1,1]],
             [[4,5,6],[2,2,2]],
             [[7,8,9],[3,3,3]]])
sss

array([[[1, 2, 3],
        [1, 1, 1]],

       [[4, 5, 6],
        [2, 2, 2]],

       [[7, 8, 9],
        [3, 3, 3]]])

In [74]:
sss.ndim

3

In [75]:
ss.size

18

In [77]:
zz.shape

(3, 3)

In [79]:
ss.shape # (3,2,3) means, its 3 dimensional and 2 first axis length, and 3 second axis length

(3, 2, 3)

In [87]:
v=np.arange(9)
v

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [89]:
vv=v.reshape(3,3)
vv

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# how to convert 1d to 2d array
# check the manual

array([[3, 4, 5]])